[Backport][SME] testsuite: Only run -fcf-protection test on i?86/x86_64 [PR107213]
Reference: https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=cc694f45087c892e69ebbb177203c708f00b1bc7

This test fails on non-i?86/x86_64 targets because on those targets
we get

  error: '-fcf-protection=full' is not supported for this target

so this patch limits where the test is run.

	PR testsuite/107213

gcc/testsuite/ChangeLog:

	* c-c++-common/pointer-to-fn1.c: Only run on i?86/x86_64.